{
 "title": "Boulderhallen",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Roccadion",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "roccadion.count" }
   ]
  },
  {
   "title": "Rockerei",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "rockerei.count" }
   ]
  },
  {
   "title": "B12",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "b12.count" }
   ]
  },
  {
   "title": "Waldau",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "waldau.count" }
   ]
  },
  {
   "title": "Active Garden",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "activegarden.count" }
   ]
  },
  {
   "title": "Auslastung Boulderhallen",
   "type": "graph",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(activegarden.count, 'Active Garden')"
    },
    {
     "target": "alias(b12.count, 'B12 Tübingen')"
    },
    {
     "target": "alias(roccadion.count, 'Roccadion')"
    },
    {
     "target": "alias(rockerei.count, 'Rockerei')"
    },
    { "target": "alias(waldau.count, 'Waldau')" }
   ]
  }
 ]
}